version: '3'
services:
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"  # Streamlit runs on port 8501
    volumes:
      - ./frontend:/app
    env_file:
      - .env  # Load environment variables from .env
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - app-network
    command: streamlit run frontend.py

  backend:
    build: 
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"  # FastAPI runs on port 8000
    volumes:
      - ./backend:/app
    env_file:
      - .env  # Load environment variables from .env
    networks:
      - app-network
    command: uvicorn backend:app --reload --host 0.0.0.0 --port 8000

networks:
  app-network:
    driver: bridge
